### ISSUE TITLE
🟢 Cada tecla tendría que tener un borde

### ISSUE THREAD

**Issue by maxiyommi** [mecantronic/teclado-virtual#10]
# Descripción
Cada tecla tendría que tener un borde (negro, azul, como ofrece la posibilidad el Plaphoons)

# Solución
Agregar borde negro solo aquellas teclas que tengan poco contraste. Por ejemplo, las letras y números (todo lo que está en el teclado gris).

**Comment by silvialuvega** [comment]
PRIORIDAD 🟡
