### ISSUE TITLE
🔴 Agregar botón pegar

### ISSUE THREAD

**Issue by maxiyommi** [mecantronic/teclado-virtual#12]
# Descripción
Cuando oprimo la tecla Copiar, aparece la leyenda “texto copiado al portapapeles. Listo para trabajar”. ¿Qué se hace luego? No tengo tecla de Pegar.

# Solución
Cambiar botón OK de leyenda, por COPIAR. La acción del botón debería copiar el texto y cerrar la leyenda.

**Comment by silvialuvega** [comment]
PRIORIDAD 🔴
