### ISSUE TITLE
🟡 Faltan teclas de signos especiales

### ISSUE THREAD

**Issue by maxiyommi** [mecantronic/teclado-virtual#7]
## Descripción:

Actualmente, el teclado de [nombre del proyecto] no incluye teclas para signos especiales, como el signo de pregunta, el signo de igual, el signo de pesos, el signo de por ciento, etc. Esto puede dificultar la escritura de textos en español, ya que es necesario usar combinaciones de teclas o menús contextuales para insertar estos signos.

## Solución propuesta:

Se propone incluir teclas dedicadas para los signos especiales más utilizados en español. Esto mejoraría la accesibilidad y la experiencia de usuario del teclado.

## Ejemplos:

* Signo de pregunta: ¿
* Signo de igual: =
* Signo de pesos: ¢
* Signo de por ciento: %

**Comment by silvialuvega** [comment]
PRIORIDAD 🟡
