### ISSUE TITLE
🔴 Agregar un botón para detener la reproducción

### ISSUE THREAD

**Issue by maxiyommi** [mecantronic/teclado-virtual#8]
## Descripción

Actualmente, el reproductor de audio no tiene un botón para detener la reproducción. Esto puede ser un inconveniente para los usuarios que desean detener la reproducción del video sin tener que cerrar la página o la aplicación.

## Solución
Para solucionar este problema, se propone agregar un botón de "Detener" al reproductor de video. Este botón se ubicaría en la esquina superior derecha del reproductor y sería visible en todo momento.
Contemplar otro botón de "Pausar".

**Comment by silvialuvega** [comment]
PRIORIDAD 🔴

**Comment by maxiyommi** [comment]
En el commit [a5f69d7](https://github.com/mecantronic/teclado-virtual/commit/a5f69d7f9e27016343484eff7e0fcf4dba139e4d), no agrega el botón "pausar".
