### ISSUE TITLE
🟡 Agregar botón para moverse por el cuadro de texto

### ISSUE THREAD

**Issue by maxiyommi** [mecantronic/teclado-virtual#9]
## Descripción
Actualmente, el único modo de desplazarse por el cuadro de texto es usando el teclado o el ratón. Esto puede ser incómodo para algunos usuarios, especialmente si tienen discapacidades físicas.

## Solución
Se propone agregar un botón para moverse por el cuadro de texto. Este botón podría estar ubicado en la parte inferior del cuadro, y permitiría desplazarse al principio, al final, al principio de la línea actual o al final de la línea actual.

**Comment by silvialuvega** [comment]
PRIORIDAD 🟡
